apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  replicas: 2

 template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello-pod
        image: nginx
        ports:
        - containerPort: 80